name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ukasyah-dev/actions/.github/workflows/deploy-github-pages.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write
    secrets: inherit
